######################## default configuration ####################
baseURL = "https://violettebelle.com/"
languageCode = "en-us"
title = "Violette Belle Calligraphy"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
# Calligraphy

[[menu.main]]
identifier = "calligraphy"
name = "Callligraphy"
URL = "/calligraphy"
weight = 1

[[menu.main]]
name = "Envelope Calligraphy"
parent = "calligraphy"
URL = "calligraphy/envelope-calligraphy/"
weight = 1

[[menu.main]]
name = "Day Of Stationery"
parent = "calligraphy"
URL = "calligraphy/day-of-stationery/"
weight = 2

[[menu.main]]
name = "Wedding Suites"
parent = "calligraphy"
URL = "calligraphy/wedding-suite-calligraphy/"
weight = 3

[[menu.main]]
name = "Fine Art Calligraphy"
parent = "calligraphy"
URL = "calligraphy/fine-art/"
weight = 4

# Illustration

# [[menu.main]]
# identifier = "illustration"
# name = "Illustration"
# URL = "/illustration"
# weight = 2

# [[menu.main]]
# name = "Wedding Crests"
# parent = "illustration"
# URL = "illustration/wedding-crests/"
# weight = 1

# [[menu.main]]
# name = "Wedding Maps"
# parent = "illustration"
# URL = "illustration/wedding-maps/"
# weight = 2

# [[menu.main]]
# name = "Bridal Portraits"
# parent = "illustration"
# URL = "illustration/bridal-portraits/"
# weight = 3

# Blog

[[menu.main]]
name = "Updates"
URL = "blog/"
weight = 45

# About

[[menu.main]]
identifier = "about"
name = "About"
URL = "about/"
weight = 50

[[menu.main]]
name = "About The Calligrapher"
parent = "about"
URL = "about/about-the-calligrapher/"
weight = 1

[[menu.main]]
name = "Process and Pricing"
parent = "about"
URL = "about/process/"
weight = 2

[[menu.main]]
name = "Fine Art Website"
parent = "about"
URL = "https://susannahfisher.art"
weight = 50

# Contact

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 60

[[menu.main]]
name = "Order Samples"
URL = "https://portal.violettebelle.com/public/form/view/6350260ab869334b6b9fd454"
weight = 65


# footer menu

[[menu.footer]]
name = "Calligraphy"
URL = "calligraphy/"
weight = 20

# [[menu.footer]]
# name = "Illustration"
# URL = "illustration/"
# weight = 25

[[menu.footer]]
name = "Process & Policies"
URL = "process/"
weight = 40

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 60

[[menu.footer]]
name = "Order Samples"
URL = "https://portal.violettebelle.com/public/form/view/6350260ab869334b6b9fd454"
weight = 65

#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "Violette Belle Calligraphy offers calligraphy services for personal stationery, weddings, and other life events."
author = "Susannah Fisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = "info@violettebelle.com"
location = ""
# copyright
copyright = "&copy; 2022 Susannah Fisher | All Rights Reserved <br> All artwork and images of artwork are the sole property of Susannah Fisher and may not be reproduced or sold for profit without written consent by the artist."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = false

############################ taxonomies ########################

[taxonomies]
  category = 'categories'
  genre = 'genres' # custom
  tag = 'tags'

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/violettebellecalligraphy/"

############################# html used in markdown ########################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

